

deploy s3:
    image:
        name: amazon/aws-cli:latest
        entrypoint: [""]
    script:
        - aws --version
        - echo "HELLO S3">file.txt
        - aws s3 cp file.txt $AWS_S3_VARIABLE/file2.txt
    stage: deploy

